In [19]:
import numpy as np
import sympy as sp
from sympy import*
from numpy import*
a=Matrix ([[1,2],[3,4],[2,5]])
a          


Matrix([
[1, 2],
[3, 4],
[2, 5]])

In [11]:
a=np.array([[1,4,5],[1,3,2]])
print(a)

[[1 4 5]
 [1 3 2]]


In [26]:
B=np.matrix('10 2 ;4 34')
print(B)

[[10  2]
 [ 4 34]]


In [28]:
print(B.shape)

(2, 2)


In [31]:
#Scaler multipication
b=np.matrix('1 2 3 4;5 6 7 8;1 2 4 3;5 4 3 2')
print(b*2)

[[ 2  4  6  8]
 [10 12 14 16]
 [ 2  4  8  6]
 [10  8  6  4]]


In [33]:
c = np.linalg.det(b)
c

-4.440892098500603e-15